@WebApi_HostAddress = http://localhost:5022/api

# @name generateAuthToken
POST {{WebApi_HostAddress}}/authentication/token
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

# @name createEvent
POST {{WebApi_HostAddress}}/events
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{generateAuthToken.response.body.$.access_token}}

{
  "name": "Test",
  "description": "Test event.",
  "location": "Online",
  "startTime": "{{$localDatetime iso8601 1 h}}",
  "endTime": "{{$localDatetime iso8601 2 h}}"
}

###

POST {{WebApi_HostAddress}}/events/{{createEvent.response.body.$.id}}/registrations
Accept: application/json
Content-Type: application/json

{
  "name": "Jane Doe",
  "phoneNumber": "+38155555555",
  "emailAddress": "jane.doe@email.com"
}

###

# @name getAllEvents
GET {{WebApi_HostAddress}}/events
Accept: application/json

###

GET {{WebApi_HostAddress}}/events/{{getAllEvents.response.body.$[0].id}}
Accept: application/json

###