@WebApi_HostAddress = http://localhost:5022/api

POST {{WebApi_HostAddress}}/events
Accept: application/json
Content-Type: application/json

{
  "name": "Test",
  "description": "Test event.",
  "location": "Online",
  "startTime": "{{$localDatetime iso8601 1 h}}",
  "endTime": "{{$localDatetime iso8601 2 h}}"
}

###